export const gameImageByTitle: Record<string, string> = {
  "Baldur's Gate 3": "https://upload.wikimedia.org/wikipedia/en/1/12/Baldur%27s_Gate_3_cover_art.jpg",
  "Elden Ring": "https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg",
  "Cyberpunk 2077": "https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg",
  "God of War Ragnarök": "https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg",
  "Black Myth: Wukong": "https://upload.wikimedia.org/wikipedia/en/a/a6/Black_Myth_Wukong_cover_art.jpg",
  "Red Dead Redemption 2": "https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg",
  "The Witcher 3: Wild Hunt": "https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg",
  "Grand Theft Auto V": "https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png",
  "Sekiro: Shadows Die Twice": "https://upload.wikimedia.org/wikipedia/en/6/6e/Sekiro_art.jpg",
  "Ghost of Tsushima": "https://upload.wikimedia.org/wikipedia/en/b/b6/Ghost_of_Tsushima.jpg",
  "Horizon Forbidden West": "https://upload.wikimedia.org/wikipedia/en/6/69/Horizon_Forbidden_West_cover_art.jpg",
  "Marvel's Spider-Man 2": "https://upload.wikimedia.org/wikipedia/en/0/0f/SpiderMan2PS5BoxArt.jpeg",
  "Starfield": "https://upload.wikimedia.org/wikipedia/en/6/6d/Bethesda_Starfield.jpg",
  "Resident Evil 4": "https://upload.wikimedia.org/wikipedia/en/d/d9/Resi4-gc-cover.jpg",
  "Helldivers 2": "https://upload.wikimedia.org/wikipedia/en/e/e7/Helldivers2cover.png",
  "Hades II": "https://upload.wikimedia.org/wikipedia/en/0/0c/Hades_2_cover_art.jpeg",
  "Palworld": "https://upload.wikimedia.org/wikipedia/en/f/fb/Palworld_Steam_artwork.jpg",
  "Final Fantasy VII Rebirth": "https://upload.wikimedia.org/wikipedia/en/7/75/Boxart_for_Final_Fantasy_VII_Rebirth.png",
  "Hogwarts Legacy": "https://upload.wikimedia.org/wikipedia/en/f/fb/Hogwarts_legacyboxart.png",
  "Monster Hunter: World": "https://upload.wikimedia.org/wikipedia/en/1/1b/Monster_Hunter_World_cover_art.jpg",
  "Alan Wake 2": "https://upload.wikimedia.org/wikipedia/en/e/ed/Alan_Wake_2_box_art.jpg",
  "Lies of P": "https://upload.wikimedia.org/wikipedia/en/d/de/Lies_of_p_cover_art.jpg",
  "Forza Horizon 5": "https://upload.wikimedia.org/wikipedia/en/8/86/Forza_Horizon_5_cover_art.jpg",
  "Counter-Strike 2": "https://upload.wikimedia.org/wikipedia/en/f/f2/CS2_Cover_Art.jpg",
  "Persona 5 Royal": "https://upload.wikimedia.org/wikipedia/en/b/b0/Persona_5_cover_art.jpg",
  "Control": "https://upload.wikimedia.org/wikipedia/en/e/e5/Control_game_cover_art.jpg",
  "No Man's Sky": "https://upload.wikimedia.org/wikipedia/en/6/67/No_Man%27s_Sky.jpg",
  "Dragon's Dogma 2": "https://upload.wikimedia.org/wikipedia/en/c/c7/Dragon%27s_Dogma_2_cover_art.jpg",
  "Diablo IV": "https://upload.wikimedia.org/wikipedia/en/1/1c/Diablo_IV_cover_art.png",
  "Metaphor: ReFantazio": "https://upload.wikimedia.org/wikipedia/en/4/4d/Metaphor_Refantazio_Cover_Art.png",
  "Warhammer 40,000: Space Marine 2": "https://upload.wikimedia.org/wikipedia/en/4/42/Warhammer_40%2C000_Space_Marine_2_cover_art.jpg",
  "Path of Exile 2": "https://upload.wikimedia.org/wikipedia/en/5/52/Path_of_Exile_2_cover_art.jpg",
  "Assassin's Creed Shadows": "https://upload.wikimedia.org/wikipedia/en/5/54/Assassin%27s_Creed_Shadows_cover.png",
  "Marvel Rivals": "https://upload.wikimedia.org/wikipedia/commons/7/70/Logo_Marvel_Rivals.png",
  "Death Stranding 2": "https://upload.wikimedia.org/wikipedia/en/e/e0/Death_Stranding_2_Icon.jpg",
  "Hollow Knight: Silksong": "https://upload.wikimedia.org/wikipedia/en/0/05/Silksong.jpg",
  "Minecraft": "https://upload.wikimedia.org/wikipedia/en/b/b6/Minecraft_2024_cover_art.png",
  "Fortnite": "https://upload.wikimedia.org/wikipedia/en/3/3a/Fortnite_cover.jpg",
  "Apex Legends": "https://upload.wikimedia.org/wikipedia/en/d/db/Apex_legends_cover.jpg",
  "VALORANT": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Valorant_logo_-_pink_color_version.svg/960px-Valorant_logo_-_pink_color_version.svg.png",
  "League of Legends": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/League_of_Legends_2019_vector.svg/960px-League_of_Legends_2019_vector.svg.png",
  "Dota 2": "https://upload.wikimedia.org/wikipedia/en/3/31/Dota_2_Steam_artwork.jpg",
  "Overwatch 2": "https://upload.wikimedia.org/wikipedia/en/8/89/Overwatch_2_Steam_artwork.jpg",
  "Rocket League": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Rocket_League_coverart.jpg",
  "Destiny 2": "https://upload.wikimedia.org/wikipedia/en/0/05/Destiny_2_%28artwork%29.jpg",
  "Tom Clancy's Rainbow Six Siege": "https://upload.wikimedia.org/wikipedia/en/4/47/Tom_Clancy%27s_Rainbow_Six_Siege_cover_art.jpg",
  "Call of Duty: Warzone": "https://upload.wikimedia.org/wikipedia/en/6/65/COD_Warzone_Cover_Art.jpg",
  "Call of Duty: Modern Warfare III": "https://upload.wikimedia.org/wikipedia/en/f/f6/MWIII_Cover_Art.png",
  "EA Sports FC 25": "https://upload.wikimedia.org/wikipedia/en/0/09/EA_FC_25_Cover.jpg",
  "NBA 2K25": "https://upload.wikimedia.org/wikipedia/en/2/2f/NBA_2K25_cover_art.jpg",
  "Gran Turismo 7": "https://upload.wikimedia.org/wikipedia/en/1/14/Gran_Turismo_7_cover_art.jpg",
  "Mario Kart 8 Deluxe": "https://upload.wikimedia.org/wikipedia/en/b/b5/MarioKart8Boxart.jpg",
  "Super Smash Bros. Ultimate": "https://upload.wikimedia.org/wikipedia/en/5/50/Super_Smash_Bros._Ultimate.jpg",
  "The Legend of Zelda: Tears of the Kingdom": "https://upload.wikimedia.org/wikipedia/en/f/fb/The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg",
  "The Legend of Zelda: Breath of the Wild": "https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg",
  "Super Mario Odyssey": "https://upload.wikimedia.org/wikipedia/en/8/8d/Super_Mario_Odyssey.jpg",
  "Super Mario Bros. Wonder": "https://upload.wikimedia.org/wikipedia/en/a/a3/Mariowonder.png",
  "Animal Crossing: New Horizons": "https://upload.wikimedia.org/wikipedia/en/1/1f/Animal_Crossing_New_Horizons.jpg",
  "Pokémon Scarlet and Violet": "https://upload.wikimedia.org/wikipedia/en/0/00/Pok%C3%A9mon_Scarlet_and_Violet_banner.png",
  "The Elder Scrolls V: Skyrim Special Edition": "https://upload.wikimedia.org/wikipedia/en/1/15/The_Elder_Scrolls_V_Skyrim_cover.png",
  "Fallout 4": "https://upload.wikimedia.org/wikipedia/en/7/70/Fallout_4_cover_art.jpg",
  "Dark Souls III": "https://upload.wikimedia.org/wikipedia/en/b/bb/Dark_souls_3_cover_art.jpg",
  "Dark Souls Remastered": "https://upload.wikimedia.org/wikipedia/en/8/8d/Dark_Souls_Cover_Art.jpg",
  "Bloodborne": "https://upload.wikimedia.org/wikipedia/en/6/68/Bloodborne_Cover_Wallpaper.jpg",
  "Demon's Souls": "https://upload.wikimedia.org/wikipedia/en/9/91/Demon%27s_Souls_Cover.jpg",
  "Armored Core VI: Fires of Rubicon": "https://upload.wikimedia.org/wikipedia/en/8/89/Armored_Core_VI_Fires_of_Rubicon_cover_art.jpg",
  "Nioh 2": "https://upload.wikimedia.org/wikipedia/en/9/91/Nioh_2_cover_art.jpg",
  "Remnant II": "https://upload.wikimedia.org/wikipedia/en/f/f1/Remnant_2_cover_art.jpg",
  "Monster Hunter Rise": "https://upload.wikimedia.org/wikipedia/en/4/41/Monster_hunter_rise_cover.jpg",
  "World of Warcraft": "https://upload.wikimedia.org/wikipedia/en/6/65/World_of_Warcraft.png",
  "Final Fantasy XIV": "https://upload.wikimedia.org/wikipedia/en/a/a1/Final_Fantasy_XIV%2C_A_Realm_Reborn_box_cover.jpg",
  "The Elder Scrolls Online": "https://upload.wikimedia.org/wikipedia/en/f/fa/Elder_Scrolls_Online_cover.png",
  "Guild Wars 2": "https://upload.wikimedia.org/wikipedia/en/9/96/Gw2-boxfront.png",
  "Genshin Impact": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Genshin_Impact_logo.svg/960px-Genshin_Impact_logo.svg.png",
  "Honkai: Star Rail": "https://upload.wikimedia.org/wikipedia/en/7/7f/Honkai_Star_Rail_%28logo%29.png",
  "Zenless Zone Zero": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Zenless_Zone_Zero_curved_box_logo.svg/250px-Zenless_Zone_Zero_curved_box_logo.svg.png",
  "Stardew Valley": "https://upload.wikimedia.org/wikipedia/en/f/fd/Logo_of_Stardew_Valley.png",
  "Terraria": "https://upload.wikimedia.org/wikipedia/en/1/1a/Terraria_Steam_artwork.jpg",
  "Hollow Knight": "https://upload.wikimedia.org/wikipedia/en/d/de/Hollow_Knight_2026_cover_art.jpg",
  "Celeste": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Celeste_box_art_full.png",
  "Cuphead": "https://upload.wikimedia.org/wikipedia/en/e/eb/Cuphead_%28artwork%29.png",
  "Dead Cells": "https://upload.wikimedia.org/wikipedia/en/1/1f/Dead_cells_cover_art.png",
  "Hades": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Detail_of_Pluto-Serapis%2C_Statue_group_of_Persephone_%28as_Isis%29_and_Pluto_%28as_Serapis%29%2C_from_the_Sanctuary_of_the_Egyptian_Gods_at_Gortyna%2C_mid-2nd_century_AD%2C_Heraklion_Archaeological_Museum_%2830305313721%29.jpg/2963px-thumbnail.jpg",
  "Vampire Survivors": "https://upload.wikimedia.org/wikipedia/en/e/e6/Vampire_Survivors_key_art.jpg",
  "Balatro": "https://upload.wikimedia.org/wikipedia/en/8/89/Balatro_cover.jpg",
  "Slay the Spire": "https://upload.wikimedia.org/wikipedia/en/b/b7/Slay_the_spire_cover.jpg",
  "Risk of Rain 2": "https://upload.wikimedia.org/wikipedia/en/c/c1/Risk_of_Rain_2.jpg",
  "Valheim": "https://upload.wikimedia.org/wikipedia/en/7/77/Valheim_2021_logo.jpg",
  "Rust": "https://upload.wikimedia.org/wikipedia/commons/a/a4/Rust_on_iron.jpg",
  "Sons of the Forest": "https://upload.wikimedia.org/wikipedia/en/3/3d/Sons_of_the_Forest.jpg",
  "ARK: Survival Ascended": "https://upload.wikimedia.org/wikipedia/en/0/06/Ark_Survival_Ascended.jpg",
  "It Takes Two": "https://upload.wikimedia.org/wikipedia/en/a/aa/It_Takes_Two_cover_art.png",
  "A Way Out": "https://upload.wikimedia.org/wikipedia/en/8/83/A_Way_Out_Logo.jpg",
  "Sid Meier's Civilization VI": "https://upload.wikimedia.org/wikipedia/en/3/3b/Civilization_VI_cover_art.jpg",
  "Age of Empires IV": "https://upload.wikimedia.org/wikipedia/en/0/08/Age_of_Empires_IV_Cover_Art.png",
  "Total War: WARHAMMER III": "https://upload.wikimedia.org/wikipedia/en/c/cb/Total_War_Warhammer_cover_art.jpg",
  "Crusader Kings III": "https://upload.wikimedia.org/wikipedia/en/a/a3/Crusader_Kings_III.jpg",
  "Portal 2": "https://upload.wikimedia.org/wikipedia/en/f/f9/Portal2cover.jpg",
  "Red Dead Redemption": "https://upload.wikimedia.org/wikipedia/en/a/a7/Red_Dead_Redemption.jpg",
  "Mass Effect Legendary Edition": "https://upload.wikimedia.org/wikipedia/en/9/97/Mass_Effect_Legendary_Edition.jpeg",
  "Star Wars Jedi: Survivor": "https://upload.wikimedia.org/wikipedia/en/4/43/Star_Wars_Jedi_Survivor.jpg",
  "Star Wars Jedi: Fallen Order": "https://upload.wikimedia.org/wikipedia/en/1/13/Cover_art_of_Star_Wars_Jedi_Fallen_Order.jpg",
  "The Last of Us Part I": "https://upload.wikimedia.org/wikipedia/en/8/86/The_Last_of_Us_Part_I_cover.jpg",
  "The Last of Us Part II Remastered": "https://upload.wikimedia.org/wikipedia/en/4/4f/TLOU_P2_Box_Art_2.png",
  "Uncharted 4: A Thief's End": "https://upload.wikimedia.org/wikipedia/en/1/1a/Uncharted_4_box_artwork.jpg",
  "Assassin's Creed Valhalla": "https://upload.wikimedia.org/wikipedia/en/f/ff/Assassin%27s_Creed_Valhalla_cover.jpg",
  "Assassin's Creed Mirage": "https://upload.wikimedia.org/wikipedia/en/2/23/Assassin%27s_Creed_Mirage_cover.jpeg",
  "Assassin's Creed Odyssey": "https://upload.wikimedia.org/wikipedia/en/9/99/ACOdysseyCoverArt.png",
  "Assassin's Creed Origins": "https://upload.wikimedia.org/wikipedia/en/4/4a/Assassin%27s_Creed_Origins_Cover_Art.png",
  "Resident Evil Village": "https://upload.wikimedia.org/wikipedia/en/2/2c/Resident_Evil_Village.png",
  "Dead Space": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Dead_Space_logo_%282023%29.svg/960px-Dead_Space_logo_%282023%29.svg.png",
  "Silent Hill 2": "https://upload.wikimedia.org/wikipedia/en/9/95/Silent_Hill_2.jpg",
  "F1 24": "https://upload.wikimedia.org/wikipedia/en/5/55/F1_24_cover_art.jpg",
  "Need for Speed Unbound": "https://upload.wikimedia.org/wikipedia/en/d/db/Need_for_Speed_Unbound.png",
  "Ori and the Will of the Wisps": "https://upload.wikimedia.org/wikipedia/en/9/94/Ori_and_the_Will_of_the_Wisps.jpg",
  "Ori and the Blind Forest": "https://upload.wikimedia.org/wikipedia/en/b/b2/Ori_and_the_Blind_Forest_Logo.jpg",
  "THE FINALS": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/The_Finals_logo_stacked.svg/4195px-The_Finals_logo_stacked.svg.png",
  "Warframe": "https://upload.wikimedia.org/wikipedia/en/b/bd/Warframe_Cover_Art.png",
  "Phasmophobia": "https://upload.wikimedia.org/wikipedia/en/f/f2/Phasmophobia_VG.jpg",
  "Tom Clancy's The Division 2": "https://upload.wikimedia.org/wikipedia/en/a/af/The_Division_2_art.jpg",
  "Sea of Thieves": "https://upload.wikimedia.org/wikipedia/en/7/77/Sea_of_thieves_cover_art.jpg",
  "Halo Infinite": "https://upload.wikimedia.org/wikipedia/en/1/14/Halo_Infinite.png",
  "XCOM 2": "https://upload.wikimedia.org/wikipedia/en/c/c3/XCOM_2_cover_art.jpg",
  "Brawlhalla": "https://upload.wikimedia.org/wikipedia/en/2/2d/Brawlhalla_BoxArt.jpg",
  "TEKKEN 8": "https://upload.wikimedia.org/wikipedia/en/0/0e/Tekken_1_game_cover.jpg",
  "Street Fighter 6": "https://upload.wikimedia.org/wikipedia/en/9/94/Street_Fighter_6_box_art.jpg",
  "Mortal Kombat 1": "https://upload.wikimedia.org/wikipedia/en/5/5b/Mortal_Kombat_1_key_art.jpeg",
  "Battlefield 2042": "https://upload.wikimedia.org/wikipedia/en/e/ec/Battlefield_2042_cover_art.jpg",
  "PUBG: BATTLEGROUNDS": "https://upload.wikimedia.org/wikipedia/en/9/9f/Pubgbattlegrounds.png",
  "Among Us": "https://upload.wikimedia.org/wikipedia/en/9/9a/Among_Us_cover_art.jpg",
  "Left 4 Dead 2": "https://upload.wikimedia.org/wikipedia/en/b/ba/Left4Dead2.jpg",
  "Team Fortress 2": "https://upload.wikimedia.org/wikipedia/en/5/5f/Tf2_standalonebox.jpg",
  "Garry's Mod": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Garry%27s_Mod_logo.svg/960px-Garry%27s_Mod_logo.svg.png",
  "Euro Truck Simulator 2": "https://upload.wikimedia.org/wikipedia/en/0/0e/Euro_Truck_Simulator_2_cover.jpg",
  "American Truck Simulator": "https://upload.wikimedia.org/wikipedia/en/2/20/American_Truck_Simulator_Steam_Cover.jpg",
  "Project Zomboid": "https://upload.wikimedia.org/wikipedia/en/0/0c/Boxshot_of_video_game_Project_zomboid.jpg",
  "DayZ": "https://upload.wikimedia.org/wikipedia/en/a/a8/Day_Z_cover.jpg",
  "RimWorld": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/294100/capsule_616x353.jpg",
  "Factorio": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/427520/capsule_616x353.jpg",
  "Satisfactory": "https://upload.wikimedia.org/wikipedia/en/0/0a/Satifactory_video_game_cover_art.jpg",
  "Dyson Sphere Program": "https://upload.wikimedia.org/wikipedia/en/0/07/Dyson_Sphere_Program_cover.jpg",
  "Oxygen Not Included": "https://upload.wikimedia.org/wikipedia/en/f/f6/Oxygen_Not_Included_cover_art.jpg",
  "Cities: Skylines": "https://upload.wikimedia.org/wikipedia/en/5/58/Cities_Skylines_cover_art.jpg",
  "Cities: Skylines II": "https://upload.wikimedia.org/wikipedia/en/3/35/Cities_Skylines_II_Cover_Art.png",
  "Hearts of Iron IV": "https://upload.wikimedia.org/wikipedia/en/b/b3/Hearts_of_Iron_IV_packshot.jpg",
  "Stellaris": "https://upload.wikimedia.org/wikipedia/en/b/bd/Stellaris_cover.png",
  "Europa Universalis IV": "https://upload.wikimedia.org/wikipedia/en/c/c5/EuropaUniversalisIV_Packshot_edited.png",
  "Total War: ROME II": "https://upload.wikimedia.org/wikipedia/en/d/da/Total_War_Rome_II_cover.jpg",
  "Mount & Blade II: Bannerlord": "https://upload.wikimedia.org/wikipedia/en/4/45/Mount_%26_Blade_II_-_Bannerlord_cover.jpg",
  "War Thunder": "https://upload.wikimedia.org/wikipedia/en/2/25/War_Thunder_PSN_Cover_Art_2015_Playstation_4.png",
  "World of Tanks": "https://upload.wikimedia.org/wikipedia/en/b/b8/World_of_Tanks.jpg",
  "The Elder Scrolls V: Skyrim": "https://upload.wikimedia.org/wikipedia/en/1/15/The_Elder_Scrolls_V_Skyrim_cover.png",
  "Fallout: New Vegas": "https://upload.wikimedia.org/wikipedia/en/3/34/Fallout_New_Vegas.jpg",
  "The Binding of Isaac: Rebirth": "https://upload.wikimedia.org/wikipedia/en/e/e1/The_Binding_of_Issac_Rebirth_cover.jpg",
  "Enter the Gungeon": "https://upload.wikimedia.org/wikipedia/en/1/16/Enter_the_Gungeon_cover_art.jpeg",
  "Don't Starve Together": "https://upload.wikimedia.org/wikipedia/en/d/d2/Don%27t_Starve_cover.jpg",
  "ASTRONEER": "https://upload.wikimedia.org/wikipedia/en/a/a9/Astroneer_cover_art.jpg",
  "Deep Rock Galactic: Survivor": "https://upload.wikimedia.org/wikipedia/en/8/89/Deep_Rock_Galactic_Survivor_cover_art.jpg",
  "V Rising": "https://upload.wikimedia.org/wikipedia/en/c/ce/V_Rising_cover_art.jpg",
  "Enshrouded": "https://upload.wikimedia.org/wikipedia/en/a/a1/Enshrouded_cover_art.jpg",
  "Ready or Not": "https://upload.wikimedia.org/wikipedia/en/3/3d/Cairn_cover_art.jpg",
  "Hell Let Loose": "https://upload.wikimedia.org/wikipedia/en/3/3e/Hell_Let_Loose_cover_art.jpg",
  "Arma 3": "https://upload.wikimedia.org/wikipedia/commons/f/fa/ArmA_3_Logo_%28Black%29.png",
  "PAYDAY 2": "https://upload.wikimedia.org/wikipedia/en/7/7b/Payday2cover.jpg",
  "For Honor": "https://upload.wikimedia.org/wikipedia/en/d/d5/For_Honor_cover_art.jpg",
  "DRAGON BALL FighterZ": "https://upload.wikimedia.org/wikipedia/en/a/ad/DBFZ_cover_art.jpg",
  "GUILTY GEAR -STRIVE-": "https://upload.wikimedia.org/wikipedia/en/8/83/Guilty_Gear_XX_PS2_JP.jpg"
};
