export type PopularGameStatus = "RELEASED" | "EARLY_ACCESS" | "UPCOMING";

export type PopularGameEntry = {
  slug: string;
  title: string;
  summary: string;
  releaseDate: string;
  status: PopularGameStatus;
  genres: string[];
  platforms: string[];
  tags: string[];
  rating: number;
  ratingsCount: number;
  dlcCount?: number;
};

const additionalSteamTitles = [
  "Half-Life",
  "Half-Life 2",
  "Half-Life: Alyx",
  "Portal",
  "Counter-Strike",
  "Counter-Strike: Source",
  "Day of Defeat",
  "Day of Defeat: Source",
  "Ricochet",
  "Deathmatch Classic",
  "Half-Life: Opposing Force",
  "Half-Life: Blue Shift",
  "Black Mesa",
  "Left 4 Dead",
  "The Stanley Parable",
  "The Stanley Parable: Ultra Deluxe",
  "The Talos Principle",
  "The Talos Principle 2",
  "Firewatch",
  "What Remains of Edith Finch",
  "INSIDE",
  "LIMBO",
  "Journey",
  "GRIS",
  "A Short Hike",
  "DREDGE",
  "Dave the Diver",
  "Sea of Stars",
  "Chained Echoes",
  "Octopath Traveler",
  "Octopath Traveler II",
  "Persona 4 Golden",
  "Persona 3 Reload",
  "Yakuza 0",
  "Like a Dragon: Infinite Wealth",
  "Like a Dragon Gaiden: The Man Who Erased His Name",
  "Judgment",
  "Lost Judgment",
  "NieR:Automata",
  "NieR Replicant ver.1.22474487139...",
  "DRAGON QUEST XI S: Echoes of an Elusive Age",
  "Monster Hunter Stories 2: Wings of Ruin",
  "Pathologic 2",
  "Disco Elysium - The Final Cut",
  "Divinity: Original Sin 2 - Definitive Edition",
  "Pillars of Eternity II: Deadfire",
  "Tyranny",
  "Wasteland 3",
  "Solasta: Crown of the Magister",
  "Warhammer 40,000: Rogue Trader",
  "Pathfinder: Wrath of the Righteous",
  "Pathfinder: Kingmaker",
  "Kingdom Come: Deliverance",
  "Mount & Blade: Warband",
  "Kenshi",
  "Battle Brothers",
  "Wartales",
  "Against the Storm",
  "FTL: Faster Than Light",
  "Into the Breach",
  "Darkest Dungeon",
  "Darkest Dungeon II",
  "Across the Obelisk",
  "Slime Rancher",
  "Slime Rancher 2",
  "Subnautica",
  "Subnautica: Below Zero",
  "Raft",
  "Grounded",
  "Core Keeper",
  "Sun Haven",
  "My Time at Sandrock",
  "Coral Island",
  "Spiritfarer: Farewell Edition",
  "Prison Architect",
  "Two Point Hospital",
  "Two Point Campus",
  "Planet Coaster",
  "Planet Zoo",
  "Cities in Motion 2",
  "Banished",
  "Timberborn",
  "Frostpunk",
  "Frostpunk 2",
  "Surviving Mars",
  "Tropico 6",
  "Anno 1800",
  "shapez 2",
  "Manor Lords",
  "Workers & Resources: Soviet Republic",
  "Songs of Conquest",
  "Heroes of Might & Magic III - HD Edition",
  "Age of Mythology: Retold",
  "Company of Heroes 3",
  "Total War: PHARAOH",
  "Total War: SHOGUN 2",
  "Total War: MEDIEVAL II - Definitive Edition",
  "Crusader Kings II",
  "Victoria 3",
  "Old World",
  "Sifu",
  "HITMAN World of Assassination",
  "Brotato",
  "Lethal Company",
  "Backpack Battles",
  "Backpack Hero",
  "Halls of Torment",
  "Holocure - Save the Fans!",
  "Noita",
  "Shadows of Doubt",
  "BattleBit Remastered",
  "Deep Rock Galactic",
  "Deep Rock Galactic: Survivor",
  "ULTRAKILL",
  "Turbo Overkill",
  "DUSK",
  "Amid Evil",
  "Warhammer 40,000: Boltgun",
  "Bomb Rush Cyberfunk",
  "Cassette Beasts",
  "Risk of Rain Returns",
  "Blasphemous",
  "Blasphemous 2",
  "The Last Faith",
  "Salt and Sanctuary",
  "Salt and Sacrifice",
  "The Messenger",
  "Katana ZERO",
  "Moonlighter",
  "Loop Hero",
  "Inscryption",
  "Cult of the Lamb",
  "Potion Craft: Alchemist Simulator",
  "Project Hospital",
  "House Flipper",
  "House Flipper 2",
  "Car Mechanic Simulator 2021",
  "Assetto Corsa",
  "Assetto Corsa Competizione",
  "Automobilista 2",
  "BeamNG.drive",
  "WRC 10 FIA World Rally Championship",
  "Need for Speed Heat",
  "Need for Speed Payback",
  "Dirt Rally 2.0",
  "GRID Legends",
  "Farming Simulator 22",
  "SnowRunner",
  "MudRunner",
  "American Fugitive",
  "Police Simulator: Patrol Officers",
  "Hunt: Showdown 1896",
] as const;

const additionalSteamGames: PopularGameEntry[] = additionalSteamTitles.map((title, index) => {
  const slug = title
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, "-")
    .replaceAll(/(^-|-$)/g, "");

  const genreSets: [string, string][] = [
    ["Action", "Adventure"],
    ["RPG", "Fantasy"],
    ["Open World", "Adventure"],
    ["Shooter", "Action"],
    ["Racing", "Simulation"],
    ["Horror", "Survival"],
    ["Strategy", "Simulation"],
    ["Fighting", "Competitive"],
  ];

  const [primaryGenre, secondaryGenre] = genreSets[index % genreSets.length];

  return {
    slug,
    title,
    summary: `${title} is a popular Steam title available for PC players.`,
    releaseDate: "2020-01-01",
    status: "RELEASED",
    genres: [primaryGenre, secondaryGenre],
    platforms: ["PC"],
    tags: ["steam", "pc", primaryGenre.toLowerCase()],
    rating: Number((7.6 + (index % 18) * 0.1).toFixed(1)),
    ratingsCount: 2500 + index * 180,
  } satisfies PopularGameEntry;
});

export const popularGames: PopularGameEntry[] = [
  {
    slug: "minecraft",
    title: "Minecraft",
    summary: "Build, survive, and explore a limitless sandbox driven by creativity and discovery.",
    releaseDate: "2011-11-18",
    status: "RELEASED",
    genres: ["Sandbox", "Survival"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["sandbox", "crafting", "co-op"],
    rating: 9.4,
    ratingsCount: 54000,
  },
  {
    slug: "apex-legends",
    title: "Apex Legends",
    summary: "Hero-based battle royale built around movement, teamwork, and high-skill gunfights.",
    releaseDate: "2019-02-04",
    status: "RELEASED",
    genres: ["Battle Royale", "FPS"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["hero shooter", "battle royale", "competitive"],
    rating: 8.5,
    ratingsCount: 42000,
  },
  {
    slug: "valorant",
    title: "VALORANT",
    summary: "Tactical round-based shooter blending precise gunplay with agent abilities.",
    releaseDate: "2020-06-02",
    status: "RELEASED",
    genres: ["Competitive Shooter", "FPS"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["tactical", "esports", "fps"],
    rating: 8.6,
    ratingsCount: 35000,
  },
  {
    slug: "league-of-legends",
    title: "League of Legends",
    summary: "The iconic 5v5 MOBA centered on strategy, mechanics, and team coordination.",
    releaseDate: "2009-10-27",
    status: "RELEASED",
    genres: ["MOBA", "Competitive"],
    platforms: ["PC"],
    tags: ["moba", "esports", "ranked"],
    rating: 8.8,
    ratingsCount: 47000,
  },
  {
    slug: "dota-2",
    title: "Dota 2",
    summary: "Deep and demanding MOBA with huge strategic depth and elite esports competition.",
    releaseDate: "2013-07-09",
    status: "RELEASED",
    genres: ["MOBA", "Strategy"],
    platforms: ["PC"],
    tags: ["moba", "strategy", "esports"],
    rating: 8.9,
    ratingsCount: 39000,
  },
  {
    slug: "overwatch-2",
    title: "Overwatch 2",
    summary: "Team-based hero shooter focused on roles, abilities, and objective control.",
    releaseDate: "2022-10-04",
    status: "RELEASED",
    genres: ["Hero Shooter", "FPS"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["hero shooter", "teamplay", "multiplayer"],
    rating: 7.9,
    ratingsCount: 23000,
  },
  {
    slug: "rocket-league",
    title: "Rocket League",
    summary: "Arcade-style car soccer with an enormous skill ceiling and competitive depth.",
    releaseDate: "2015-07-07",
    status: "RELEASED",
    genres: ["Sports", "Competitive"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["cars", "esports", "multiplayer"],
    rating: 8.7,
    ratingsCount: 31000,
  },
  {
    slug: "destiny-2",
    title: "Destiny 2",
    summary: "Shared-world looter shooter featuring raids, seasonal progression, and sci-fi lore.",
    releaseDate: "2017-09-06",
    status: "RELEASED",
    genres: ["Looter Shooter", "FPS"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["loot", "co-op", "raids"],
    rating: 8.3,
    ratingsCount: 26000,
    dlcCount: 6,
  },
  {
    slug: "tom-clancys-rainbow-six-siege",
    title: "Tom Clancy's Rainbow Six Siege",
    summary: "Tactical close-quarters shooter built around operators, gadgets, and map knowledge.",
    releaseDate: "2015-12-01",
    status: "RELEASED",
    genres: ["Tactical Shooter", "FPS"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["tactical", "operators", "competitive"],
    rating: 8.2,
    ratingsCount: 28000,
  },
  {
    slug: "call-of-duty-warzone",
    title: "Call of Duty: Warzone",
    summary: "Large-scale battle royale with fast gunplay and squad-focused tactics.",
    releaseDate: "2020-03-10",
    status: "RELEASED",
    genres: ["Battle Royale", "FPS"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["battle royale", "fps", "squads"],
    rating: 8.1,
    ratingsCount: 33000,
  },
  {
    slug: "call-of-duty-modern-warfare-iii",
    title: "Call of Duty: Modern Warfare III",
    summary: "Blockbuster shooter campaign and multiplayer with frequent live updates.",
    releaseDate: "2023-11-10",
    status: "RELEASED",
    genres: ["Action", "FPS"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["cod", "multiplayer", "shooter"],
    rating: 7.6,
    ratingsCount: 14000,
  },
  {
    slug: "ea-sports-fc-25",
    title: "EA Sports FC 25",
    summary: "Global football simulation with licensed clubs, seasons, and online competition.",
    releaseDate: "2024-09-27",
    status: "RELEASED",
    genres: ["Sports", "Simulation"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["football", "sports", "online"],
    rating: 7.8,
    ratingsCount: 8700,
  },
  {
    slug: "nba-2k25",
    title: "NBA 2K25",
    summary: "Basketball sim franchise with career modes, online play, and team building.",
    releaseDate: "2024-09-06",
    status: "RELEASED",
    genres: ["Sports", "Simulation"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["basketball", "sports", "career"],
    rating: 7.7,
    ratingsCount: 6200,
  },
  {
    slug: "gran-turismo-7",
    title: "Gran Turismo 7",
    summary: "Premium racing simulation with detailed car handling and track variety.",
    releaseDate: "2022-03-04",
    status: "RELEASED",
    genres: ["Racing", "Simulation"],
    platforms: ["PS5", "PS4"],
    tags: ["racing", "sim", "cars"],
    rating: 8.5,
    ratingsCount: 9800,
  },
  {
    slug: "mario-kart-8-deluxe",
    title: "Mario Kart 8 Deluxe",
    summary: "Party racing classic with polished tracks, items, and local or online chaos.",
    releaseDate: "2017-04-28",
    status: "RELEASED",
    genres: ["Racing", "Party"],
    platforms: ["Switch"],
    tags: ["party", "racing", "family"],
    rating: 9.1,
    ratingsCount: 22500,
    dlcCount: 1,
  },
  {
    slug: "super-smash-bros-ultimate",
    title: "Super Smash Bros. Ultimate",
    summary: "Massive crossover fighting game with deep mechanics and huge character variety.",
    releaseDate: "2018-12-07",
    status: "RELEASED",
    genres: ["Fighting", "Party"],
    platforms: ["Switch"],
    tags: ["fighting", "party", "multiplayer"],
    rating: 9.0,
    ratingsCount: 18400,
  },
  {
    slug: "the-legend-of-zelda-tears-of-the-kingdom",
    title: "The Legend of Zelda: Tears of the Kingdom",
    summary: "Open-air adventure focused on exploration, creative tools, and emergent gameplay.",
    releaseDate: "2023-05-12",
    status: "RELEASED",
    genres: ["Adventure", "Open World"],
    platforms: ["Switch"],
    tags: ["exploration", "adventure", "puzzle"],
    rating: 9.7,
    ratingsCount: 26000,
  },
  {
    slug: "the-legend-of-zelda-breath-of-the-wild",
    title: "The Legend of Zelda: Breath of the Wild",
    summary: "Genre-defining open-world adventure built around freedom and environmental systems.",
    releaseDate: "2017-03-03",
    status: "RELEASED",
    genres: ["Adventure", "Open World"],
    platforms: ["Switch"],
    tags: ["open world", "exploration", "adventure"],
    rating: 9.8,
    ratingsCount: 32000,
  },
  {
    slug: "super-mario-odyssey",
    title: "Super Mario Odyssey",
    summary: "Playful 3D platforming journey packed with inventive worlds and movement.",
    releaseDate: "2017-10-27",
    status: "RELEASED",
    genres: ["Platformer", "Adventure"],
    platforms: ["Switch"],
    tags: ["platformer", "family", "adventure"],
    rating: 9.6,
    ratingsCount: 21400,
  },
  {
    slug: "super-mario-bros-wonder",
    title: "Super Mario Bros. Wonder",
    summary: "A vibrant side-scrolling platformer with creative power-ups and multiplayer fun.",
    releaseDate: "2023-10-20",
    status: "RELEASED",
    genres: ["Platformer", "Party"],
    platforms: ["Switch"],
    tags: ["platformer", "co-op", "family"],
    rating: 9.0,
    ratingsCount: 9800,
  },
  {
    slug: "animal-crossing-new-horizons",
    title: "Animal Crossing: New Horizons",
    summary: "Relaxing life sim about island design, collecting, and social creativity.",
    releaseDate: "2020-03-20",
    status: "RELEASED",
    genres: ["Life Sim", "Casual"],
    platforms: ["Switch"],
    tags: ["cozy", "life sim", "creative"],
    rating: 8.9,
    ratingsCount: 28700,
  },
  {
    slug: "pokemon-scarlet-and-violet",
    title: "Pokémon Scarlet and Violet",
    summary: "Open-world monster collecting RPG with co-op exploration and battles.",
    releaseDate: "2022-11-18",
    status: "RELEASED",
    genres: ["JRPG", "Adventure"],
    platforms: ["Switch"],
    tags: ["pokemon", "rpg", "collecting"],
    rating: 8.0,
    ratingsCount: 13200,
  },
  {
    slug: "skyrim-special-edition",
    title: "The Elder Scrolls V: Skyrim Special Edition",
    summary: "Classic open-world fantasy RPG known for freedom, mods, and exploration.",
    releaseDate: "2016-10-28",
    status: "RELEASED",
    genres: ["RPG", "Open World"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["rpg", "open world", "mods"],
    rating: 9.2,
    ratingsCount: 30100,
  },
  {
    slug: "fallout-4",
    title: "Fallout 4",
    summary: "Post-apocalyptic action RPG with exploration, crafting, and settlement building.",
    releaseDate: "2015-11-10",
    status: "RELEASED",
    genres: ["Action RPG", "Open World"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["post-apocalyptic", "rpg", "crafting"],
    rating: 8.6,
    ratingsCount: 23400,
  },
  {
    slug: "dark-souls-3",
    title: "Dark Souls III",
    summary: "Atmospheric and challenging action RPG with iconic bosses and lore.",
    releaseDate: "2016-04-12",
    status: "RELEASED",
    genres: ["Action RPG", "Soulslike"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["soulslike", "boss fights", "challenge"],
    rating: 9.3,
    ratingsCount: 24500,
  },
  {
    slug: "dark-souls-remastered",
    title: "Dark Souls Remastered",
    summary: "The foundational soulslike experience with deliberate combat and world design.",
    releaseDate: "2018-05-25",
    status: "RELEASED",
    genres: ["Action RPG", "Soulslike"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["soulslike", "classic", "dark fantasy"],
    rating: 9.1,
    ratingsCount: 16300,
  },
  {
    slug: "bloodborne",
    title: "Bloodborne",
    summary: "Gothic action RPG with aggressive combat and haunting cosmic horror themes.",
    releaseDate: "2015-03-24",
    status: "RELEASED",
    genres: ["Action RPG", "Horror"],
    platforms: ["PS5"],
    tags: ["soulslike", "horror", "gothic"],
    rating: 9.5,
    ratingsCount: 19800,
  },
  {
    slug: "demons-souls",
    title: "Demon's Souls",
    summary: "Stunning remake of the game that established modern soulslike design.",
    releaseDate: "2020-11-12",
    status: "RELEASED",
    genres: ["Action RPG", "Soulslike"],
    platforms: ["PS5"],
    tags: ["soulslike", "remake", "dark fantasy"],
    rating: 8.9,
    ratingsCount: 8400,
  },
  {
    slug: "armored-core-vi-fires-of-rubicon",
    title: "Armored Core VI: Fires of Rubicon",
    summary: "High-speed mech action with deep customization and explosive boss battles.",
    releaseDate: "2023-08-25",
    status: "RELEASED",
    genres: ["Action", "Mecha"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["mech", "action", "customization"],
    rating: 8.8,
    ratingsCount: 7300,
  },
  {
    slug: "nioh-2",
    title: "Nioh 2",
    summary: "Fast and technical samurai action RPG with deep combat systems.",
    releaseDate: "2020-03-13",
    status: "RELEASED",
    genres: ["Action RPG", "Soulslike"],
    platforms: ["PC", "PS5"],
    tags: ["samurai", "soulslike", "loot"],
    rating: 8.7,
    ratingsCount: 9200,
  },
  {
    slug: "remnant-2",
    title: "Remnant II",
    summary: "Co-op shooter soulslike with procedural worlds, builds, and tough bosses.",
    releaseDate: "2023-07-25",
    status: "RELEASED",
    genres: ["Action", "Co-op Shooter"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["co-op", "soulslike", "shooter"],
    rating: 8.5,
    ratingsCount: 6100,
  },
  {
    slug: "monster-hunter-rise",
    title: "Monster Hunter Rise",
    summary: "Agile monster hunting with wirebug mobility and deep weapon mastery.",
    releaseDate: "2021-03-26",
    status: "RELEASED",
    genres: ["Action RPG", "Co-op"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["monster hunting", "co-op", "action"],
    rating: 8.8,
    ratingsCount: 11100,
  },
  {
    slug: "world-of-warcraft",
    title: "World of Warcraft",
    summary: "Long-running MMORPG with raids, dungeons, and expansive fantasy lore.",
    releaseDate: "2004-11-23",
    status: "RELEASED",
    genres: ["MMORPG", "Fantasy"],
    platforms: ["PC"],
    tags: ["mmorpg", "raids", "fantasy"],
    rating: 8.9,
    ratingsCount: 26000,
    dlcCount: 10,
  },
  {
    slug: "final-fantasy-xiv",
    title: "Final Fantasy XIV",
    summary: "Story-rich MMORPG praised for expansions, raids, and cooperative play.",
    releaseDate: "2013-08-27",
    status: "RELEASED",
    genres: ["MMORPG", "JRPG"],
    platforms: ["PC", "PS5"],
    tags: ["mmorpg", "story", "raids"],
    rating: 9.1,
    ratingsCount: 18800,
    dlcCount: 5,
  },
  {
    slug: "elder-scrolls-online",
    title: "The Elder Scrolls Online",
    summary: "Online Elder Scrolls adventure with large zones, dungeons, and role-based builds.",
    releaseDate: "2014-04-04",
    status: "RELEASED",
    genres: ["MMORPG", "Fantasy"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["mmorpg", "elder scrolls", "co-op"],
    rating: 8.2,
    ratingsCount: 12600,
  },
  {
    slug: "guild-wars-2",
    title: "Guild Wars 2",
    summary: "Accessible MMORPG focused on dynamic events and build experimentation.",
    releaseDate: "2012-08-28",
    status: "RELEASED",
    genres: ["MMORPG", "Fantasy"],
    platforms: ["PC"],
    tags: ["mmorpg", "events", "co-op"],
    rating: 8.4,
    ratingsCount: 9400,
  },
  {
    slug: "genshin-impact",
    title: "Genshin Impact",
    summary: "Open-world action RPG with elemental combat and gacha character progression.",
    releaseDate: "2020-09-28",
    status: "RELEASED",
    genres: ["Action RPG", "Open World"],
    platforms: ["PC", "PS5", "Xbox", "Mobile"],
    tags: ["anime", "gacha", "open world"],
    rating: 8.4,
    ratingsCount: 20500,
  },
  {
    slug: "honkai-star-rail",
    title: "Honkai: Star Rail",
    summary: "Turn-based sci-fi RPG with stylish presentation and character collection.",
    releaseDate: "2023-04-26",
    status: "RELEASED",
    genres: ["JRPG", "Turn-Based"],
    platforms: ["PC", "PS5", "Mobile"],
    tags: ["turn-based", "anime", "gacha"],
    rating: 8.5,
    ratingsCount: 12400,
  },
  {
    slug: "zenless-zone-zero",
    title: "Zenless Zone Zero",
    summary: "Stylish urban action RPG with fast combat and character-driven squads.",
    releaseDate: "2024-07-04",
    status: "RELEASED",
    genres: ["Action RPG", "Sci-Fi"],
    platforms: ["PC", "PS5", "Mobile"],
    tags: ["action", "anime", "urban fantasy"],
    rating: 8.1,
    ratingsCount: 5600,
  },
  {
    slug: "stardew-valley",
    title: "Stardew Valley",
    summary: "Beloved indie farming sim with social progression and relaxing routines.",
    releaseDate: "2016-02-26",
    status: "RELEASED",
    genres: ["Life Sim", "Indie"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["cozy", "farming", "indie"],
    rating: 9.3,
    ratingsCount: 28400,
  },
  {
    slug: "terraria",
    title: "Terraria",
    summary: "2D sandbox adventure packed with crafting, bosses, and exploration.",
    releaseDate: "2011-05-16",
    status: "RELEASED",
    genres: ["Sandbox", "Adventure"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["sandbox", "crafting", "bosses"],
    rating: 9.2,
    ratingsCount: 33200,
  },
  {
    slug: "hollow-knight",
    title: "Hollow Knight",
    summary: "Atmospheric metroidvania with precise combat and interconnected world design.",
    releaseDate: "2017-02-24",
    status: "RELEASED",
    genres: ["Metroidvania", "Indie"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["metroidvania", "indie", "challenge"],
    rating: 9.4,
    ratingsCount: 19500,
  },
  {
    slug: "celeste",
    title: "Celeste",
    summary: "Critically acclaimed platformer combining difficult gameplay with heartfelt storytelling.",
    releaseDate: "2018-01-25",
    status: "RELEASED",
    genres: ["Platformer", "Indie"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["platformer", "indie", "precision"],
    rating: 9.2,
    ratingsCount: 12100,
  },
  {
    slug: "cuphead",
    title: "Cuphead",
    summary: "Stylized run-and-gun game known for hand-drawn art and difficult boss fights.",
    releaseDate: "2017-09-29",
    status: "RELEASED",
    genres: ["Action", "Indie"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["boss rush", "indie", "co-op"],
    rating: 8.8,
    ratingsCount: 10900,
    dlcCount: 1,
  },
  {
    slug: "dead-cells",
    title: "Dead Cells",
    summary: "Fast roguelite action platformer with build variety and smooth combat loops.",
    releaseDate: "2018-08-07",
    status: "RELEASED",
    genres: ["Roguelike", "Action"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["roguelike", "indie", "action"],
    rating: 9.0,
    ratingsCount: 9800,
    dlcCount: 4,
  },
  {
    slug: "hades",
    title: "Hades",
    summary: "Award-winning action roguelike blending myth, narrative, and satisfying combat.",
    releaseDate: "2020-09-17",
    status: "RELEASED",
    genres: ["Roguelike", "Action"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["roguelike", "story", "indie"],
    rating: 9.3,
    ratingsCount: 17200,
  },
  {
    slug: "vampire-survivors",
    title: "Vampire Survivors",
    summary: "Auto-attacking survival roguelite with addictive progression and huge builds.",
    releaseDate: "2022-10-20",
    status: "RELEASED",
    genres: ["Roguelike", "Indie"],
    platforms: ["PC", "PS5", "Xbox", "Switch", "Mobile"],
    tags: ["indie", "survival", "roguelike"],
    rating: 8.9,
    ratingsCount: 8800,
  },
  {
    slug: "balatro",
    title: "Balatro",
    summary: "Poker-inspired roguelike deckbuilder with brilliant run variety and combos.",
    releaseDate: "2024-02-20",
    status: "RELEASED",
    genres: ["Roguelike", "Card Game"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["deckbuilder", "indie", "roguelike"],
    rating: 9.1,
    ratingsCount: 6200,
  },
  {
    slug: "slay-the-spire",
    title: "Slay the Spire",
    summary: "Genre-defining deckbuilding roguelike known for strategic depth and replayability.",
    releaseDate: "2019-01-23",
    status: "RELEASED",
    genres: ["Roguelike", "Card Game"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["deckbuilder", "strategy", "indie"],
    rating: 9.2,
    ratingsCount: 14200,
  },
  {
    slug: "risk-of-rain-2",
    title: "Risk of Rain 2",
    summary: "Co-op roguelike shooter with scaling chaos and build synergies.",
    releaseDate: "2020-08-11",
    status: "RELEASED",
    genres: ["Roguelike", "Shooter"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["co-op", "roguelike", "shooter"],
    rating: 8.8,
    ratingsCount: 9700,
  },
  {
    slug: "valheim",
    title: "Valheim",
    summary: "Viking-themed survival crafting game with excellent co-op exploration.",
    releaseDate: "2021-02-02",
    status: "RELEASED",
    genres: ["Survival", "Open World"],
    platforms: ["PC", "Xbox"],
    tags: ["survival", "crafting", "co-op"],
    rating: 8.8,
    ratingsCount: 14900,
  },
  {
    slug: "rust",
    title: "Rust",
    summary: "Hardcore survival sandbox centered on base building, raids, and PvP.",
    releaseDate: "2018-02-08",
    status: "RELEASED",
    genres: ["Survival", "Multiplayer"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["survival", "pvp", "crafting"],
    rating: 8.0,
    ratingsCount: 15500,
  },
  {
    slug: "sons-of-the-forest",
    title: "Sons of the Forest",
    summary: "Survival horror crafting sequel with base defense and open-ended exploration.",
    releaseDate: "2024-02-22",
    status: "RELEASED",
    genres: ["Survival", "Horror"],
    platforms: ["PC"],
    tags: ["survival", "horror", "co-op"],
    rating: 8.1,
    ratingsCount: 7300,
  },
  {
    slug: "ark-survival-ascended",
    title: "ARK: Survival Ascended",
    summary: "Dinosaur survival sandbox rebuilt with modern visuals and systems.",
    releaseDate: "2023-10-26",
    status: "RELEASED",
    genres: ["Survival", "Open World"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["dinosaurs", "survival", "base building"],
    rating: 7.8,
    ratingsCount: 4800,
  },
  {
    slug: "it-takes-two",
    title: "It Takes Two",
    summary: "Creative co-op adventure built entirely around two-player teamwork.",
    releaseDate: "2021-03-26",
    status: "RELEASED",
    genres: ["Co-op", "Adventure"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["co-op", "adventure", "puzzle"],
    rating: 9.1,
    ratingsCount: 11800,
  },
  {
    slug: "a-way-out",
    title: "A Way Out",
    summary: "Narrative co-op prison-break adventure designed for two players only.",
    releaseDate: "2018-03-23",
    status: "RELEASED",
    genres: ["Co-op", "Narrative"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["co-op", "story", "split-screen"],
    rating: 8.2,
    ratingsCount: 6800,
  },
  {
    slug: "civilization-vi",
    title: "Sid Meier's Civilization VI",
    summary: "Turn-based grand strategy game about building an empire through the ages.",
    releaseDate: "2016-10-21",
    status: "RELEASED",
    genres: ["Strategy", "Turn-Based"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["4x", "strategy", "turn-based"],
    rating: 9.0,
    ratingsCount: 16400,
    dlcCount: 2,
  },
  {
    slug: "age-of-empires-iv",
    title: "Age of Empires IV",
    summary: "Modern RTS entry focused on historical factions and macro strategy.",
    releaseDate: "2021-10-28",
    status: "RELEASED",
    genres: ["Strategy", "RTS"],
    platforms: ["PC", "Xbox"],
    tags: ["rts", "historical", "competitive"],
    rating: 8.6,
    ratingsCount: 7600,
  },
  {
    slug: "total-war-warhammer-iii",
    title: "Total War: WARHAMMER III",
    summary: "Hybrid grand strategy and real-time battles in the Warhammer fantasy world.",
    releaseDate: "2022-02-17",
    status: "RELEASED",
    genres: ["Strategy", "RTS"],
    platforms: ["PC"],
    tags: ["strategy", "warhammer", "grand strategy"],
    rating: 8.3,
    ratingsCount: 6900,
    dlcCount: 3,
  },
  {
    slug: "crusader-kings-iii",
    title: "Crusader Kings III",
    summary: "Character-driven grand strategy where dynasties rise and fall across centuries.",
    releaseDate: "2020-09-01",
    status: "RELEASED",
    genres: ["Strategy", "Grand Strategy"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["grand strategy", "roleplay", "medieval"],
    rating: 8.9,
    ratingsCount: 8400,
  },
  {
    slug: "portal-2",
    title: "Portal 2",
    summary: "Puzzle masterpiece featuring inventive mechanics and legendary writing.",
    releaseDate: "2011-04-19",
    status: "RELEASED",
    genres: ["Puzzle", "Narrative"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["puzzle", "co-op", "classic"],
    rating: 9.7,
    ratingsCount: 28600,
  },
  {
    slug: "red-dead-redemption",
    title: "Red Dead Redemption",
    summary: "Western open-world classic centered on redemption and frontier drama.",
    releaseDate: "2010-05-18",
    status: "RELEASED",
    genres: ["Open World", "Adventure"],
    platforms: ["PS5", "Xbox", "Switch"],
    tags: ["western", "story", "open world"],
    rating: 9.2,
    ratingsCount: 13200,
  },
  {
    slug: "mass-effect-legendary-edition",
    title: "Mass Effect Legendary Edition",
    summary: "Remastered sci-fi RPG trilogy known for companions and branching choices.",
    releaseDate: "2021-05-14",
    status: "RELEASED",
    genres: ["RPG", "Sci-Fi"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["rpg", "story", "sci-fi"],
    rating: 9.1,
    ratingsCount: 10200,
  },
  {
    slug: "star-wars-jedi-survivor",
    title: "Star Wars Jedi: Survivor",
    summary: "Cinematic action adventure with lightsaber combat and metroidvania exploration.",
    releaseDate: "2023-04-28",
    status: "RELEASED",
    genres: ["Action", "Adventure"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["star wars", "action", "story"],
    rating: 8.6,
    ratingsCount: 9300,
  },
  {
    slug: "star-wars-jedi-fallen-order",
    title: "Star Wars Jedi: Fallen Order",
    summary: "Story-focused action adventure blending lightsaber combat and exploration.",
    releaseDate: "2019-11-15",
    status: "RELEASED",
    genres: ["Action", "Adventure"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["star wars", "action", "adventure"],
    rating: 8.7,
    ratingsCount: 12100,
  },
  {
    slug: "the-last-of-us-part-i",
    title: "The Last of Us Part I",
    summary: "Emotionally driven post-apocalyptic journey with survival and stealth combat.",
    releaseDate: "2022-09-02",
    status: "RELEASED",
    genres: ["Action", "Narrative"],
    platforms: ["PC", "PS5"],
    tags: ["story", "survival", "cinematic"],
    rating: 9.3,
    ratingsCount: 9700,
  },
  {
    slug: "the-last-of-us-part-ii-remastered",
    title: "The Last of Us Part II Remastered",
    summary: "Critically acclaimed narrative action sequel with expanded PS5 presentation.",
    releaseDate: "2024-01-19",
    status: "RELEASED",
    genres: ["Action", "Narrative"],
    platforms: ["PS5"],
    tags: ["story", "cinematic", "action"],
    rating: 9.0,
    ratingsCount: 7400,
  },
  {
    slug: "uncharted-4-a-thiefs-end",
    title: "Uncharted 4: A Thief's End",
    summary: "Cinematic treasure-hunting adventure with polished action set pieces.",
    releaseDate: "2016-05-10",
    status: "RELEASED",
    genres: ["Action", "Adventure"],
    platforms: ["PC", "PS5"],
    tags: ["cinematic", "adventure", "story"],
    rating: 9.1,
    ratingsCount: 12600,
  },
  {
    slug: "assassins-creed-valhalla",
    title: "Assassin's Creed Valhalla",
    summary: "Viking-era open-world action RPG featuring raids, exploration, and progression.",
    releaseDate: "2020-11-10",
    status: "RELEASED",
    genres: ["Action RPG", "Open World"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["open world", "stealth", "historical"],
    rating: 8.1,
    ratingsCount: 14800,
  },
  {
    slug: "assassins-creed-mirage",
    title: "Assassin's Creed Mirage",
    summary: "Stealth-focused return to classic Assassin's Creed city-scale design.",
    releaseDate: "2023-10-05",
    status: "RELEASED",
    genres: ["Action", "Stealth"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["stealth", "assassins creed", "action"],
    rating: 7.9,
    ratingsCount: 6500,
  },
  {
    slug: "assassins-creed-odyssey",
    title: "Assassin's Creed Odyssey",
    summary: "Massive historical open-world RPG set in ancient Greece.",
    releaseDate: "2018-10-05",
    status: "RELEASED",
    genres: ["Action RPG", "Open World"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["historical", "open world", "rpg"],
    rating: 8.6,
    ratingsCount: 17300,
  },
  {
    slug: "assassins-creed-origins",
    title: "Assassin's Creed Origins",
    summary: "The RPG reboot entry featuring Egypt exploration and revamped combat.",
    releaseDate: "2017-10-27",
    status: "RELEASED",
    genres: ["Action RPG", "Open World"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["egypt", "open world", "rpg"],
    rating: 8.4,
    ratingsCount: 13200,
  },
  {
    slug: "resident-evil-village",
    title: "Resident Evil Village",
    summary: "First-person survival horror with memorable villains and tense encounters.",
    releaseDate: "2021-05-07",
    status: "RELEASED",
    genres: ["Survival Horror", "Action"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["horror", "survival", "resident evil"],
    rating: 8.8,
    ratingsCount: 10900,
  },
  {
    slug: "dead-space-remake",
    title: "Dead Space",
    summary: "Modern remake of a sci-fi survival horror classic with atmospheric dread.",
    releaseDate: "2023-01-27",
    status: "RELEASED",
    genres: ["Survival Horror", "Sci-Fi"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["horror", "remake", "sci-fi"],
    rating: 8.9,
    ratingsCount: 7500,
  },
  {
    slug: "silent-hill-2-remake",
    title: "Silent Hill 2",
    summary: "Psychological horror remake focused on atmosphere, tension, and symbolism.",
    releaseDate: "2024-10-08",
    status: "RELEASED",
    genres: ["Horror", "Narrative"],
    platforms: ["PC", "PS5"],
    tags: ["psychological horror", "remake", "story"],
    rating: 8.7,
    ratingsCount: 4200,
  },
  {
    slug: "f1-24",
    title: "F1 24",
    summary: "Official Formula 1 racing sim with licensed teams and career progression.",
    releaseDate: "2024-05-31",
    status: "RELEASED",
    genres: ["Racing", "Simulation"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["formula 1", "racing", "sim"],
    rating: 7.9,
    ratingsCount: 3900,
  },
  {
    slug: "need-for-speed-unbound",
    title: "Need for Speed Unbound",
    summary: "Arcade street racing with stylized visuals and high-speed police chases.",
    releaseDate: "2022-12-02",
    status: "RELEASED",
    genres: ["Racing", "Arcade"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["racing", "arcade", "street"],
    rating: 7.8,
    ratingsCount: 5100,
  },
  {
    slug: "ori-and-the-will-of-the-wisps",
    title: "Ori and the Will of the Wisps",
    summary: "Beautiful metroidvania platformer with emotional storytelling and fluid movement.",
    releaseDate: "2020-03-11",
    status: "RELEASED",
    genres: ["Metroidvania", "Platformer"],
    platforms: ["PC", "Xbox", "Switch"],
    tags: ["metroidvania", "platformer", "story"],
    rating: 9.2,
    ratingsCount: 8900,
  },
  {
    slug: "ori-and-the-blind-forest",
    title: "Ori and the Blind Forest",
    summary: "Acclaimed platforming adventure with stunning art and precise controls.",
    releaseDate: "2015-03-11",
    status: "RELEASED",
    genres: ["Metroidvania", "Platformer"],
    platforms: ["PC", "Xbox", "Switch"],
    tags: ["metroidvania", "platformer", "indie"],
    rating: 9.0,
    ratingsCount: 9700,
  },
  {
    slug: "the-finals",
    title: "THE FINALS",
    summary: "Team shooter with destructible arenas and high-tempo objective play.",
    releaseDate: "2023-12-07",
    status: "RELEASED",
    genres: ["Shooter", "Multiplayer"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["fps", "destruction", "competitive"],
    rating: 8.1,
    ratingsCount: 6700,
  },
  {
    slug: "warframe",
    title: "Warframe",
    summary: "Free-to-play co-op looter shooter with deep progression and mobility.",
    releaseDate: "2013-03-25",
    status: "RELEASED",
    genres: ["Action", "Looter Shooter"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["co-op", "loot", "sci-fi"],
    rating: 8.6,
    ratingsCount: 15400,
  },
  {
    slug: "phasmophobia",
    title: "Phasmophobia",
    summary: "Co-op ghost investigation horror game powered by teamwork and tension.",
    releaseDate: "2020-09-18",
    status: "EARLY_ACCESS",
    genres: ["Horror", "Co-op"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["co-op", "horror", "investigation"],
    rating: 8.5,
    ratingsCount: 7900,
  },
  {
    slug: "the-division-2",
    title: "Tom Clancy's The Division 2",
    summary: "Cover-based looter shooter with build crafting and endgame activities.",
    releaseDate: "2019-03-15",
    status: "RELEASED",
    genres: ["Looter Shooter", "Action"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["loot", "co-op", "cover shooter"],
    rating: 8.0,
    ratingsCount: 8800,
  },
  {
    slug: "sea-of-thieves",
    title: "Sea of Thieves",
    summary: "Shared-world pirate adventure built around emergent crew stories.",
    releaseDate: "2018-03-20",
    status: "RELEASED",
    genres: ["Adventure", "Multiplayer"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["pirates", "co-op", "sandbox"],
    rating: 8.4,
    ratingsCount: 9300,
  },
  {
    slug: "halo-infinite",
    title: "Halo Infinite",
    summary: "Flagship sci-fi shooter with open-zone campaign and competitive multiplayer.",
    releaseDate: "2021-12-08",
    status: "RELEASED",
    genres: ["FPS", "Action"],
    platforms: ["PC", "Xbox"],
    tags: ["halo", "fps", "multiplayer"],
    rating: 8.2,
    ratingsCount: 10800,
  },
  {
    slug: "xcom-2",
    title: "XCOM 2",
    summary: "Turn-based tactical strategy game with high-stakes squad management.",
    releaseDate: "2016-02-05",
    status: "RELEASED",
    genres: ["Strategy", "Turn-Based"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["tactical", "turn-based", "strategy"],
    rating: 8.9,
    ratingsCount: 9200,
  },
  {
    slug: "brawlhalla",
    title: "Brawlhalla",
    summary: "Free-to-play platform fighter with frequent crossovers and online modes.",
    releaseDate: "2017-10-17",
    status: "RELEASED",
    genres: ["Fighting", "Multiplayer"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["fighting", "free-to-play", "multiplayer"],
    rating: 7.9,
    ratingsCount: 8400,
  },
  {
    slug: "tekken-8",
    title: "TEKKEN 8",
    summary: "Flagship 3D fighting game with modern visuals and deep competitive systems.",
    releaseDate: "2024-01-26",
    status: "RELEASED",
    genres: ["Fighting", "Competitive"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["fighting", "esports", "multiplayer"],
    rating: 8.9,
    ratingsCount: 6700,
  },
  {
    slug: "street-fighter-6",
    title: "Street Fighter 6",
    summary: "A polished fighting game with strong online play and broad character depth.",
    releaseDate: "2023-06-02",
    status: "RELEASED",
    genres: ["Fighting", "Competitive"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["fighting", "competitive", "online"],
    rating: 9.0,
    ratingsCount: 8900,
  },
  {
    slug: "mortal-kombat-1",
    title: "Mortal Kombat 1",
    summary: "Brutal fighting reboot with cinematic story and signature finishing moves.",
    releaseDate: "2023-09-19",
    status: "RELEASED",
    genres: ["Fighting", "Action"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["fighting", "story", "multiplayer"],
    rating: 8.4,
    ratingsCount: 7600,
  },
  {
    slug: "battlefield-2042",
    title: "Battlefield 2042",
    summary: "Large-scale warfare shooter focused on dynamic maps and combined arms combat.",
    releaseDate: "2021-11-19",
    status: "RELEASED",
    genres: ["Shooter", "FPS"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["fps", "multiplayer", "large scale"],
    rating: 7.5,
    ratingsCount: 9500,
  },
  {
    slug: "pubg-battlegrounds",
    title: "PUBG: BATTLEGROUNDS",
    summary: "Classic battle royale emphasizing survival, positioning, and gun skill.",
    releaseDate: "2017-12-20",
    status: "RELEASED",
    genres: ["Battle Royale", "Shooter"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["battle royale", "survival", "shooter"],
    rating: 8.0,
    ratingsCount: 19400,
  },
  {
    slug: "among-us",
    title: "Among Us",
    summary: "Social deduction multiplayer game centered on teamwork and deception.",
    releaseDate: "2018-11-16",
    status: "RELEASED",
    genres: ["Party", "Multiplayer"],
    platforms: ["PC", "PS5", "Xbox", "Switch", "Mobile"],
    tags: ["party", "social deduction", "multiplayer"],
    rating: 8.1,
    ratingsCount: 16300,
  },
  {
    slug: "left-4-dead-2",
    title: "Left 4 Dead 2",
    summary: "Legendary co-op zombie shooter with endless replayability and workshop support.",
    releaseDate: "2009-11-17",
    status: "RELEASED",
    genres: ["Co-op Shooter", "Horror"],
    platforms: ["PC"],
    tags: ["co-op", "zombies", "classic"],
    rating: 9.1,
    ratingsCount: 28200,
  },
  {
    slug: "team-fortress-2",
    title: "Team Fortress 2",
    summary: "Class-based multiplayer shooter known for personality, depth, and long-term community play.",
    releaseDate: "2007-10-10",
    status: "RELEASED",
    genres: ["Shooter", "Multiplayer"],
    platforms: ["PC"],
    tags: ["class-based", "fps", "free-to-play"],
    rating: 8.8,
    ratingsCount: 31800,
  },
  {
    slug: "garrys-mod",
    title: "Garry's Mod",
    summary: "Sandbox physics playground powered by creativity, mods, and community servers.",
    releaseDate: "2006-11-29",
    status: "RELEASED",
    genres: ["Sandbox", "Multiplayer"],
    platforms: ["PC"],
    tags: ["sandbox", "mods", "community"],
    rating: 8.9,
    ratingsCount: 19800,
  },
  {
    slug: "euro-truck-simulator-2",
    title: "Euro Truck Simulator 2",
    summary: "Relaxing logistics sim with deep route planning and long-haul progression.",
    releaseDate: "2012-10-18",
    status: "RELEASED",
    genres: ["Simulation", "Driving"],
    platforms: ["PC"],
    tags: ["sim", "driving", "relaxing"],
    rating: 8.8,
    ratingsCount: 14700,
    dlcCount: 10,
  },
  {
    slug: "american-truck-simulator",
    title: "American Truck Simulator",
    summary: "Open-road trucking sim across iconic American highways and cities.",
    releaseDate: "2016-02-02",
    status: "RELEASED",
    genres: ["Simulation", "Driving"],
    platforms: ["PC"],
    tags: ["sim", "trucking", "open road"],
    rating: 8.6,
    ratingsCount: 9200,
    dlcCount: 8,
  },
  {
    slug: "project-zomboid",
    title: "Project Zomboid",
    summary: "Hardcore isometric zombie survival sandbox with deep systems and emergent storytelling.",
    releaseDate: "2013-11-08",
    status: "EARLY_ACCESS",
    genres: ["Survival", "Sandbox"],
    platforms: ["PC"],
    tags: ["survival", "zombies", "hardcore"],
    rating: 8.9,
    ratingsCount: 11600,
  },
  {
    slug: "dayz",
    title: "DayZ",
    summary: "Persistent open-world survival focused on tension, scavenging, and player encounters.",
    releaseDate: "2018-12-13",
    status: "RELEASED",
    genres: ["Survival", "Open World"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["survival", "pvp", "open world"],
    rating: 8.1,
    ratingsCount: 11200,
  },
  {
    slug: "rimworld",
    title: "RimWorld",
    summary: "Colony simulation storyteller where every run creates memorable survival drama.",
    releaseDate: "2018-10-17",
    status: "RELEASED",
    genres: ["Simulation", "Strategy"],
    platforms: ["PC"],
    tags: ["colony", "sim", "story generator"],
    rating: 9.4,
    ratingsCount: 12600,
    dlcCount: 4,
  },
  {
    slug: "factorio",
    title: "Factorio",
    summary: "Factory-building strategy masterpiece centered on automation and optimization.",
    releaseDate: "2020-08-14",
    status: "RELEASED",
    genres: ["Strategy", "Simulation"],
    platforms: ["PC"],
    tags: ["automation", "factory", "strategy"],
    rating: 9.5,
    ratingsCount: 14100,
  },
  {
    slug: "satisfactory",
    title: "Satisfactory",
    summary: "First-person factory-building game with massive automation chains and co-op.",
    releaseDate: "2020-06-08",
    status: "RELEASED",
    genres: ["Simulation", "Sandbox"],
    platforms: ["PC"],
    tags: ["factory", "automation", "co-op"],
    rating: 8.8,
    ratingsCount: 9800,
  },
  {
    slug: "dyson-sphere-program",
    title: "Dyson Sphere Program",
    summary: "Interstellar factory simulation where you industrialize planets and stars.",
    releaseDate: "2021-01-21",
    status: "RELEASED",
    genres: ["Simulation", "Strategy"],
    platforms: ["PC"],
    tags: ["factory", "space", "automation"],
    rating: 8.7,
    ratingsCount: 7600,
  },
  {
    slug: "oxygen-not-included",
    title: "Oxygen Not Included",
    summary: "Complex colony sim about resource management, engineering, and survival underground.",
    releaseDate: "2019-07-30",
    status: "RELEASED",
    genres: ["Simulation", "Strategy"],
    platforms: ["PC"],
    tags: ["colony", "management", "sim"],
    rating: 8.7,
    ratingsCount: 6900,
  },
  {
    slug: "cities-skylines",
    title: "Cities: Skylines",
    summary: "City-building sim with deep planning tools and expansive modding support.",
    releaseDate: "2015-03-10",
    status: "RELEASED",
    genres: ["Simulation", "Strategy"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["city builder", "management", "sim"],
    rating: 8.9,
    ratingsCount: 10100,
    dlcCount: 8,
  },
  {
    slug: "cities-skylines-ii",
    title: "Cities: Skylines II",
    summary: "Modern city-builder sequel with advanced simulation depth and larger scale systems.",
    releaseDate: "2023-10-24",
    status: "RELEASED",
    genres: ["Simulation", "Strategy"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["city builder", "simulation", "strategy"],
    rating: 7.9,
    ratingsCount: 4300,
  },
  {
    slug: "hearts-of-iron-iv",
    title: "Hearts of Iron IV",
    summary: "World War grand strategy focused on diplomacy, production, and military campaigns.",
    releaseDate: "2016-06-06",
    status: "RELEASED",
    genres: ["Grand Strategy", "Strategy"],
    platforms: ["PC"],
    tags: ["ww2", "grand strategy", "war"],
    rating: 8.6,
    ratingsCount: 11300,
    dlcCount: 8,
  },
  {
    slug: "stellaris",
    title: "Stellaris",
    summary: "Space grand strategy game with empire building, diplomacy, and exploration.",
    releaseDate: "2016-05-09",
    status: "RELEASED",
    genres: ["Grand Strategy", "Sci-Fi"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["space", "grand strategy", "4x"],
    rating: 8.5,
    ratingsCount: 9800,
    dlcCount: 8,
  },
  {
    slug: "europa-universalis-iv",
    title: "Europa Universalis IV",
    summary: "Historical grand strategy sandbox spanning diplomacy, trade, and conquest.",
    releaseDate: "2013-08-13",
    status: "RELEASED",
    genres: ["Grand Strategy", "Strategy"],
    platforms: ["PC"],
    tags: ["history", "grand strategy", "empire"],
    rating: 8.3,
    ratingsCount: 8700,
    dlcCount: 8,
  },
  {
    slug: "total-war-rome-ii",
    title: "Total War: ROME II",
    summary: "Iconic strategy game combining empire management and large-scale tactical battles.",
    releaseDate: "2013-09-02",
    status: "RELEASED",
    genres: ["Strategy", "RTS"],
    platforms: ["PC"],
    tags: ["strategy", "history", "tactics"],
    rating: 8.1,
    ratingsCount: 7300,
  },
  {
    slug: "mount-and-blade-ii-bannerlord",
    title: "Mount & Blade II: Bannerlord",
    summary: "Medieval sandbox blending real-time battles, kingdom politics, and RPG progression.",
    releaseDate: "2022-10-25",
    status: "RELEASED",
    genres: ["RPG", "Strategy"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["medieval", "sandbox", "strategy"],
    rating: 8.4,
    ratingsCount: 8200,
  },
  {
    slug: "war-thunder",
    title: "War Thunder",
    summary: "Combined-arms military combat sim with air, land, and naval warfare.",
    releaseDate: "2016-08-15",
    status: "RELEASED",
    genres: ["Simulation", "Action"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["military", "vehicles", "multiplayer"],
    rating: 7.8,
    ratingsCount: 12000,
  },
  {
    slug: "world-of-tanks",
    title: "World of Tanks",
    summary: "Team-based armored warfare game featuring tactical vehicle combat.",
    releaseDate: "2011-04-12",
    status: "RELEASED",
    genres: ["Action", "Simulation"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["tanks", "pvp", "military"],
    rating: 7.7,
    ratingsCount: 9100,
  },
  {
    slug: "the-elder-scrolls-v-skyrim",
    title: "The Elder Scrolls V: Skyrim",
    summary: "Genre-defining open-world fantasy RPG renowned for freedom and modding.",
    releaseDate: "2011-11-11",
    status: "RELEASED",
    genres: ["RPG", "Open World"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["rpg", "open world", "fantasy"],
    rating: 9.3,
    ratingsCount: 26500,
  },
  {
    slug: "fallout-new-vegas",
    title: "Fallout: New Vegas",
    summary: "Fan-favorite RPG with branching choices and deep faction-driven storytelling.",
    releaseDate: "2010-10-19",
    status: "RELEASED",
    genres: ["RPG", "Open World"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["rpg", "choices", "post-apocalyptic"],
    rating: 9.1,
    ratingsCount: 12800,
  },
  {
    slug: "the-binding-of-isaac-rebirth",
    title: "The Binding of Isaac: Rebirth",
    summary: "Influential roguelike shooter with massive item variety and replay value.",
    releaseDate: "2014-11-04",
    status: "RELEASED",
    genres: ["Roguelike", "Indie"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["roguelike", "indie", "dungeon"],
    rating: 8.9,
    ratingsCount: 10100,
    dlcCount: 4,
  },
  {
    slug: "enter-the-gungeon",
    title: "Enter the Gungeon",
    summary: "Bullet-hell roguelike with creative weapons, co-op, and polished combat loops.",
    releaseDate: "2016-04-05",
    status: "RELEASED",
    genres: ["Roguelike", "Action"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["roguelike", "bullet hell", "indie"],
    rating: 8.8,
    ratingsCount: 6700,
  },
  {
    slug: "don-t-starve-together",
    title: "Don't Starve Together",
    summary: "Co-op survival crafting game with distinctive art style and relentless challenge.",
    releaseDate: "2016-04-21",
    status: "RELEASED",
    genres: ["Survival", "Co-op"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["survival", "co-op", "crafting"],
    rating: 8.6,
    ratingsCount: 9200,
  },
  {
    slug: "astroneer",
    title: "ASTRONEER",
    summary: "Colorful space survival sandbox with terraforming, automation, and co-op exploration.",
    releaseDate: "2019-02-06",
    status: "RELEASED",
    genres: ["Survival", "Sandbox"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["space", "survival", "co-op"],
    rating: 8.3,
    ratingsCount: 6100,
  },
  {
    slug: "deep-rock-galactic-survivor",
    title: "Deep Rock Galactic: Survivor",
    summary: "Auto-shooter spinoff delivering dense waves, mining, and fast session progression.",
    releaseDate: "2024-02-14",
    status: "EARLY_ACCESS",
    genres: ["Roguelike", "Action"],
    platforms: ["PC"],
    tags: ["roguelike", "horde", "survivor"],
    rating: 8.4,
    ratingsCount: 3600,
  },
  {
    slug: "v-rising",
    title: "V Rising",
    summary: "Vampire survival action RPG focused on base building and boss hunting.",
    releaseDate: "2024-05-08",
    status: "RELEASED",
    genres: ["Survival", "Action RPG"],
    platforms: ["PC", "PS5"],
    tags: ["vampire", "survival", "crafting"],
    rating: 8.5,
    ratingsCount: 6400,
  },
  {
    slug: "enshrouded",
    title: "Enshrouded",
    summary: "Open-world survival crafting RPG with cooperative base building and combat.",
    releaseDate: "2024-01-24",
    status: "EARLY_ACCESS",
    genres: ["Survival", "Action RPG"],
    platforms: ["PC"],
    tags: ["survival", "crafting", "co-op"],
    rating: 8.0,
    ratingsCount: 5200,
  },
  {
    slug: "ready-or-not",
    title: "Ready or Not",
    summary: "Tactical SWAT shooter emphasizing realism, communication, and methodical room clearing.",
    releaseDate: "2023-12-13",
    status: "RELEASED",
    genres: ["Tactical Shooter", "FPS"],
    platforms: ["PC"],
    tags: ["tactical", "co-op", "realism"],
    rating: 8.4,
    ratingsCount: 7500,
  },
  {
    slug: "hell-let-loose",
    title: "Hell Let Loose",
    summary: "Hardcore tactical WWII shooter with large team battles and strategic coordination.",
    releaseDate: "2021-07-27",
    status: "RELEASED",
    genres: ["Shooter", "Simulation"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["ww2", "tactical", "multiplayer"],
    rating: 8.2,
    ratingsCount: 6800,
  },
  {
    slug: "arma-3",
    title: "Arma 3",
    summary: "Military sandbox sim with combined arms, modding, and large-scale scenarios.",
    releaseDate: "2013-09-12",
    status: "RELEASED",
    genres: ["Simulation", "Shooter"],
    platforms: ["PC"],
    tags: ["milsim", "sandbox", "mods"],
    rating: 8.5,
    ratingsCount: 8900,
  },
  {
    slug: "payday-2",
    title: "PAYDAY 2",
    summary: "Co-op heist shooter centered on planning, stealth options, and progression.",
    releaseDate: "2013-08-13",
    status: "RELEASED",
    genres: ["Co-op Shooter", "Action"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["heist", "co-op", "shooter"],
    rating: 8.3,
    ratingsCount: 10400,
    dlcCount: 8,
  },
  {
    slug: "for-honor",
    title: "For Honor",
    summary: "Melee-focused multiplayer action game with faction warfare and dueling depth.",
    releaseDate: "2017-02-14",
    status: "RELEASED",
    genres: ["Action", "Fighting"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["melee", "multiplayer", "combat"],
    rating: 7.9,
    ratingsCount: 7200,
  },
  {
    slug: "dragon-ball-fighterz",
    title: "DRAGON BALL FighterZ",
    summary: "High-energy anime fighter with strong visuals and competitive team battles.",
    releaseDate: "2018-01-26",
    status: "RELEASED",
    genres: ["Fighting", "Competitive"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    tags: ["anime", "fighting", "competitive"],
    rating: 8.6,
    ratingsCount: 6100,
  },
  {
    slug: "guilty-gear-strive",
    title: "GUILTY GEAR -STRIVE-",
    summary: "Stylish anime fighter with precise mechanics and strong online rollback play.",
    releaseDate: "2021-06-11",
    status: "RELEASED",
    genres: ["Fighting", "Competitive"],
    platforms: ["PC", "PS5", "Xbox"],
    tags: ["fighting", "anime", "esports"],
    rating: 8.7,
    ratingsCount: 4300,
  },
  ...additionalSteamGames,
];